<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- This is RobuROC model for gazebo simulation -->
    <!-- Model visualisation and collision is made of simple shapes box and cylinders-->

    <!-- All links get friction coefficients and as Gazebo don't read collors they specifeid again-->
    <gazebo reference="chassis_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="wheel_1_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel_2_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel_3_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel_4_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="IMU_link">
        <mu1> 0.2 </mu1>
        <mu2> 0.2 </mu2>
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo>
        <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
            <jointName>wheel_1_joint,wheel_2_joint,wheel_3_joint,wheel_4_joint</jointName>
        </plugin>
    </gazebo>
<!-- #################################################################################### -->
<!--                                Differential drive                                    -->
<!-- #################################################################################### -->
    <gazebo>
        <!-- Gazebo plugin for differential drive -->
        <plugin name="skid_steer_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace> </namespace>
            </ros>

            <num_wheel_pairs>2</num_wheel_pairs>

            <!-- Wheels 0 -->
            <left_joint>wheel_1_joint</left_joint>
            <right_joint>wheel_2_joint</right_joint>
        
            <!-- Wheels 1 -->
            <left_joint>wheel_4_joint</left_joint>
            <right_joint>wheel_3_joint</right_joint>

            <!-- Kinematics -->
            <wheel_separation>${box_y+cyl_l}</wheel_separation>
            <wheel_separation>${box_y+cyl_l}</wheel_separation>

            <wheel_diameter>${cyl_r*2}</wheel_diameter>
            <wheel_diameter>${cyl_r*2}</wheel_diameter>

            <!-- Limits -->
            <max_wheel_torque>1000</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>

            <!-- Output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
    
        </plugin>
    </gazebo>

</robot>
